sonar.projectKey=react-map-app
sonar.projectName=React Map App
sonar.projectVersion=1.0
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=
sonar.host.url=http://localhost:9000
sonar.login=squ_bed8f8bf86a355331c3146061fcde9c3b28435b2
